- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: remove the default content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Download and Extract
  include_role:
    name: common
    tasks_from: download

- name: copy the content to nginx path
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: copy config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes