
#1. Update SystemD file with correct IP addresses
#
#Update `MONGO_DNSNAME` with MongoDB Server IP
#
#2. Now, lets set up the service with systemctl.

- name: Configure YUM repos
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install the required packages
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Add app User
  ansible.builtin.user:
    name: roboshop
    comment: roboshop project applicatopn user

- name: Download and Extrat
  include_role:
    name: common
    tasks_from: download

- name: cleanup the old content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy the content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop

- name: Install nodeJS dependencies
  community.general.npm:
    path: /home/roboshop/catalogue

- name: copy systemd  file
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Strat  catalogue service
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_realod: yes




