#!/bin/bash

frontend:
	bash Components/frontend.sh

cart:
	bash Components/cart.sh

catalouge:
	bash Components/Catalouge.sh

dispatch:
	bash Components/Dispatch.sh

mongodb:
	bash Components/Mongodb.sh

mysql:
	bash Components/MYSql.sh

payment:
	bash Components/Payment.sh

rabbitmq:
	bash Components/RabbitMQ.sh

redis:
	bash Components/redis.sh

shipping:
	bash Components/shipping.sh

user:
	bash Components/user.sh